version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: istomshop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4961025Ir
      POSTGRES_DB: istomshop
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: istomshop_backend
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 4961025Ir
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: istomshop
      JWT_SECRET: sadfeafsdk
      BACKEND_URL: http://localhost:3075/public/images
      PORT: 3075
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: roziisomiddinov@gmail.com
      SMTP_PASS: 4961025IRB
    ports:
      - "3075:3075"
    depends_on:
      - postgres
